language: cpp
compiler:
    - g++

before_install:
    - sudo apt-get -y install gdb
    - pip install --user cpp-coveralls

install:
    # get c++11 support
    - export CXX="g++-5" CC="gcc-5"
    - ulimit -c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - gcc-5
            - g++-5

before_script:
    - ulimit -c unlimited -S

script:
    - RESULT=0
    - make prepare
    - make benchmark-all CXX=g++-5 PRELOAD_LIB=
    - make benchmark-bwtree CXX=g++-5 PRELOAD_LIB=
    - make clean
    - make test CXX=g++-5 OPT_FLAG=-fprofile-arcs -ftest-coverage PRELOAD_LIB= || RESULT=$?
    - if [[ ${RESULT} == 0 ]]; then echo "\\o/ Test worked without problems"; else echo "Test returned an errorcode of $RESULT"; fi;
    - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
    - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi;

after_success:
    - coveralls -t NZ5M6jFefl1w4w7aCVCLDuK4GfOWMFYiW
